# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ea5ad2a62b1ac97d8193d38df7a4fae97a4aa87afe37cb9a017d00e38e8c162b06da54062860ddf8bf6b429ee9aeada25d9803295881cb18f92014db33b01ab

test:
  secret_key_base: 1a3837a89541017dfde271d9c8ac71f74eb02925d158c5b6f65d0d95dc30a1b1451f2b3e6a5f01b3f53756b11ad39de759c3c74a04d6e6df3353cc27fca0b59f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
